apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testdocs
  annotations:
    github.com/project-slug: waqasali47/testdocs
spec:
  type: other
  lifecycle: unknown
  owner: my-group
